theme="amp"
baseurl = "http://arnesen.tech"
title = "Alexander Arnesen"
paginate = 10
copyright = "© 2016 Arnesen Tech"
canonifyurls = true
publishdir = "docs"
googleAnalytics = "UA-87922334-1" # optional

# optional

 [[menu.header]]
    name = "Instagram"
    weight = 2
    url = "https://instagram.com/alxarn"

  [[menu.header]]
    name = "Photography"
    weight = 3
    url = "http://arnesen.photography"

  [[menu.header]]
    name = "Github"
    weight = 4
    url = "https://github.com/Arnesen"
