baseurl = "https://www.example.com"
languageCode = "en"
title = "Alexander Arnesen"
theme = "Kiss"
copyright = ""
googleAnalytics = "UA-87922334-1"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true 
publishDir = "docs"


[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "AlxArn"
github = "Arnesen"
email = ""
linkedin = ""
facebook = ""
instagram = "alxarn"
codepen = ""

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true